// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WK5X1HjHr_YAwAshzQ7PvBQCC9b1hXY',
    appId: '1:935041312791:web:5ad5ec8ccc3beaff4c9452',
    messagingSenderId: '935041312791',
    projectId: 'employee-registration-44df8',
    authDomain: 'employee-registration-44df8.firebaseapp.com',
    storageBucket: 'employee-registration-44df8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqmu8cJniN8FYeyMppeUB9neiPxo8f9Cw',
    appId: '1:935041312791:android:400c401a91ecfa5d4c9452',
    messagingSenderId: '935041312791',
    projectId: 'employee-registration-44df8',
    storageBucket: 'employee-registration-44df8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyvdrPgws3GDU-zIZC9z0eUW2Jmb6B22c',
    appId: '1:935041312791:ios:f4ff7e453c922b2f4c9452',
    messagingSenderId: '935041312791',
    projectId: 'employee-registration-44df8',
    storageBucket: 'employee-registration-44df8.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyvdrPgws3GDU-zIZC9z0eUW2Jmb6B22c',
    appId: '1:935041312791:ios:f4ff7e453c922b2f4c9452',
    messagingSenderId: '935041312791',
    projectId: 'employee-registration-44df8',
    storageBucket: 'employee-registration-44df8.firebasestorage.app',
    iosBundleId: 'com.example.employeeFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8WK5X1HjHr_YAwAshzQ7PvBQCC9b1hXY',
    appId: '1:935041312791:web:83d998ea60d12a434c9452',
    messagingSenderId: '935041312791',
    projectId: 'employee-registration-44df8',
    authDomain: 'employee-registration-44df8.firebaseapp.com',
    storageBucket: 'employee-registration-44df8.firebasestorage.app',
  );
}
